language: python
python:
  - "3.6"
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest