language: python
python:
  - "3.6"
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install django-rest-framework
  - pip install django-model-utils
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=django_logic/ ./tests/manage.py test
after_success:
  - coveralls