# Generated by Django 6.0.4 on 2026-06-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='audit_status',
            field=models.CharField(default='clean', max_length=32),
        ),
    ]
