# Generated by Django 6.0.4 on 2026-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_tests', '0002_widget_audit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivableWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='draft', max_length=32)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
