# Generated by Django 6.0.4 on 2026-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_tests', '0003_archivablewidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', max_length=32)),
                ('source_integration', models.CharField(default='gmail', max_length=32)),
                ('se_log', models.TextField(blank=True, default='')),
                ('cb_log', models.TextField(blank=True, default='')),
            ],
        ),
    ]
