# Generated by Django 6.1 on 2026-08-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg_tests', '0004_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetProxyA',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bg_tests.widget',),
        ),
        migrations.CreateModel(
            name='WidgetProxyB',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bg_tests.widget',),
        ),
    ]
